spring.application.name=assignment-backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://root:YCfMouihHiALGkDuKMuMDAkxawrveuXi@shortline.proxy.rlwy.net:54857/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=YCfMouihHiALGkDuKMuMDAkxawrveuXi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.jwt.secret=${APP_JWT_SECRET:ChangeThisSecretKeyBeforeProductionChangeThisSecretKey}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
app.file-storage-path=${APP_FILE_STORAGE_PATH:uploads}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}

management.endpoints.web.exposure.include=health,info
management.health.mail.enabled=false
